### ISSUE TITLE
mentioning bazel-msbuild in the Bazel newsletter for Bazel 0.12.0?

### ISSUE THREAD

**Issue by laszlocsomor** [tmandry/bazel-msbuild#1]
Hi,

I'm Laszlo and I work on Bazel-on-Windows. We found your tool a couple of weeks ago and I think it would be really useful to some of our users! Would you mind if we mentioned it in the newsletter for the upcoming Bazel release?

I'd like to phrase it like so:

> Tools:
> - Tyler Mandry wrote a Visual Studio project generator for C++ rules: https://github.com/tmandry/bazel-msbuild

Please let me know what you think!

/cc @philwo

**Comment by tmandry** [comment]
Hi Laszlo! I would be happy if you featured the project. The wording sounds good. I just updated the README so it's slightly less barebones.

Thanks!

**Comment by tmandry** [comment]
Also, let me know if you have suggestions for wording changes or clarification to the README or anything else.

**Comment by laszlocsomor** [comment]
Hi Tyler,

Great, thank you! I'll add this entry to the newsletter then.

The only thing I noticed in the README is in the "Usage" section: it's not clear which terminal the user should run the commands in, `cmd.exe` or MSYS Bash. Otherwise it looks good, it's simple and clear!

Cheers,
Laszlo

**Comment by tmandry** [comment]
Hey @laszlocsomor, congrats on a successful 0.12 release!

Odd timing perhaps, but FYI, I just changed the project name to Lavender. I'd also like to request that the announcement in the blog post be converted to links instead of text URLs. Those URLs aren't clickable on the blog.

Thanks for the announcement!

**Comment by philwo** [comment]
FYI @laurentlb for the blog post

**Comment by laurentlb** [comment]
You can send a PR here: https://github.com/bazelbuild/bazel-blog/blob/master/_posts/2018-04-11-bazel-0.12.md

(I think all links have been fixed now)

**Comment by tmandry** [comment]
Ah, did not know about the repo. Looks like everything is fixed now. Thanks!
